---
- name: Install and start Apache on web servers
  hosts: webservers
  become: yes  # Run tasks with sudo (privilege escalation)
  
  tasks:
    - name: Install Apache (httpd)
      yum:
        name: httpd
        state: present

    - name: Ensure Apache is started and enabled
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Create custom index.html from template
      template:
        src: index.html.j2
        dest: /var/www/html/index.html

    - name: Ensure Apache is restarted to load new index.html
      service:
        name: httpd
        state: restarted
